server:
  port: 8091

spring:
  application:
    name: service-consumer03

#  redis 连接配置
  redis:
    host: localhost
    port: 6379
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
