server:
  port: 8080

spring:
  application:
    name: service-consumer-${server.port}

#  redis 连接配置
  redis:
    host: localhost
    port: 6379
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
