server:
  port: 8091

spring:
  application:
#    指定当前微服务对外（提供者）暴露的服务名称
    name: jade-stream-kafka
  cloud:
    stream:
      kafka:
        binder:
#          指定stream 连接 kafka集群
          brokers: localhost:9092
#          指定是否自动创建主题
          auto-create-topics: true
      bindings:
        output: #指定要输出的消息主题和类型
          destination: names
          content-type: text/plain
        test: # 指定自定义 要输出的消息主题和类型
          destination: citys
          content-type: text/plain

        input:
          destination: names

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
