

spring:
#  application:
#    name: dubbo-provider-5

  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.nengrui.evcharger.server.model
  type-aliases-package: com.jade.serviceprovider.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8090


logging:
#  pattern:
#    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descripter.sql.BasicBinder: trace
    org.hibernate.type.descripter.sql.BasicExtractor: trace
    com.abc.msc: debug
