server:
  port: 8091
spring:
  application:
    name: service-consumer03
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka


feign:
  client:
    config:
      default:
        conectionTimeout: 5000 # 指定Feign连接提供者的超时时间
        readTimeout: 5000 # 指定Feign从请求到获取提供者响应的超时时间

# 开启feign 对 hystrix 的支持
  hystrix:
    enabled: true
#修改负载均衡策略
#service-provider02: # 要负载均衡的提供者微服务名称
#  ribbon: # 指定要使用的负载均衡策略
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

#hystrix:
#  command:
#    default:  #default全局有效，service id指定应用有效
#      execution:
#        timeout:
#          enabled: true
#          # 如果enabled设置为false，则请求超时交给ribbon控制,此时@HystrixProperty(name = "execution.isolation
#          #.thread.timeoutInMilliseconds", value = "5000")不起效
#          # 如果enabled设置为true, 则hystrix也有对超时的控制权，@HystrixProperty(name = "execution.isolation
#          #.thread.timeoutInMilliseconds", value = "5000")起效果
#          # 且如果enabled设置为true，ribbon，hystrix都有对请求超时的控制权，且控制效果一样
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000