server:
  port: 8480

spring:
  application:
    name: service-consumer

#  redis 连接配置
  redis:
    host: localhost
    port: 6379
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    metadata-map:
      hostmark: running-host