server:
  # 配置服务端口
  port: 9999


spring:
  cloud:
    config:
      server:
        git:
#          指定git远程仓库地址
#          uri: https://github.com/Asurada520/jade-config-center.git
          uri: https://gitee.com/Asurada520/jade-config-center.git
#          指定获取到git远程仓库连接的超时时间，默认为5秒
          timeout: 5
#          指定要操作的远程仓库的分支，默认 master
          default-label: master
          force-pull: true
          username: 602423940@qq.com
          password: liya5211314