server:
  port: 8091
spring:
  application:
    name: service-consumer02

  zipkin:
    # 指定zipkin服务器地址
#    base-url: http://localhost:9411/
    sender:
      type: kafka
  kafka:
      bootstrap-servers: kafkaOS:9092
  sleuth:
      # 设置采样比列为1.0， 即全部需要，默认为0.1
      sampler:
        probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
